# Generated by Django 5.2.15 on 2026-06-09 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_lead_date_alter_lead_date_of_meeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='date_of_meeting',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='final_status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='mode_of_meeting',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_action_plan',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='revenue_expected',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.AddField(
            model_name='lead',
            name='ae_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='closures',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='demo_call',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='linkedin_connect',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='meeting_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='outcome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='proposal_sent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
