# Generated by Django 4.2.30 on 2026-06-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_eodreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eodreport',
            name='calls_done',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eodreport',
            name='emails_sent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eodreport',
            name='follow_ups_done',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eodreport',
            name='meetings_attended',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eodreport',
            name='meetings_fixed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eodreport',
            name='pipeline_added',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eodreport',
            name='target_calls',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eodreport',
            name='target_emails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eodreport',
            name='target_follow_ups',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eodreport',
            name='target_meetings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
