# Generated by Django 4.2.30 on 2026-06-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_lead_contact_person_lead_annual_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='annual_revenue',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='corporate',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='crm_employee_count',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='crm_purpose',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='department',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='dependent_feature',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='employee_counts',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='expected_closure_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='gst_name_bank_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='gst_no',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='hrms_employee_count',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='hrms_purpose',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='net_disb_amount',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='purpose_of_buying_hrms',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='region',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sub_lead_source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='tds',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='team_members_using_crm',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='total_sales_value',
        ),
        migrations.AddField(
            model_name='lead',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='date_of_meeting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='final_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='mode_of_meeting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='revenue_expected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
