# Generated by Django 4.2.30 on 2026-06-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_lead_annual_revenue_remove_lead_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_of_meeting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
