# Generated by Django 4.2.30 on 2026-06-09 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0005_remove_lead_assigned_to_remove_lead_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EODReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls_done', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('follow_ups_done', models.IntegerField(default=0)),
                ('meetings_fixed', models.IntegerField(default=0)),
                ('meetings_attended', models.IntegerField(default=0)),
                ('pipeline_added', models.CharField(blank=True, max_length=100, null=True)),
                ('key_highlights', models.TextField(blank=True, null=True)),
                ('target_calls', models.IntegerField(default=0)),
                ('target_emails', models.IntegerField(default=0)),
                ('target_follow_ups', models.IntegerField(default=0)),
                ('target_meetings', models.IntegerField(default=0)),
                ('key_deals_focus', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eod_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
