# Generated by Django 5.2.15 on 2026-06-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_eodreport_calls_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_interaction_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='call_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
