# Generated by Django 5.2.15 on 2026-06-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_lead_call_interaction_time_lead_call_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
