# Generated by Django 5.2.15 on 2026-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_lead_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='conversation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
