# Generated by Django 5.2.15 on 2026-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_lead_conversation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_outcome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
