# Generated by Django 5.2.15 on 2026-06-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_lead_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='eodreport',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
